# Generated by Django 4.0.6 on 2022-09-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_participant_meetup_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default='xxx@mail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
